### ISSUE TITLE
Illustrative Language Understanding: Large-Scale Visual Grounding with Image Search Jamie

### ISSUE THREAD

**Issue by NomotoEriko** [OnizukaLab/ConferenceProceedings#17]
## 一言でいうと
単語分散表現を画像に基づいて獲得する手法を提案

### 論文リンク
http://aclweb.org/anthology/P18-1085

### 著者/所属機関
J. Kiros, W. Chan, G. Hinton
Google Brain Toronto

## 概要
* 単語から Google 画像検索してその上位10件をCNNに突っ込んで concat して単語分散表現 **Picturebook** の出来上がり
* Glove （などの他の単語分散表現）との併用手法である **multimodal Fusion Gating** 
* Picturebook から単語を得る **Inverse Picturebook** 
* 様々な NLP タスクで分析

## 新規性・差分
単語分散表現の獲得に画像を用いること

## 手法
* 単語から Google 画像検索してその上位10件をCNNに突っ込んで concat
* CNN は意味的順位付けを学習したもの
* 意味的順位付けに用いるデータセットは，視覚的類似度ベースと意味的類似度ベースのそれぞれを試して意味的類似度ベースの方がいいことがわかった
* multimodal Gating はいわゆるアテンションっぽい機構
* Inverse Picturebook はデコーダの内部状態をターゲット言語側の Picturebook に近づけるような機構

### 類似単語
![image](https://user-images.githubusercontent.com/19987739/45597513-8180b280-ba08-11e8-82db-f685774e680f.png)

### 単語類似度のよさ（SimLex-999で評価）
![image](https://user-images.githubusercontent.com/19987739/45597524-aaa14300-ba08-11e8-8db3-59db6072ce67.png)

### 自然言語推論
![image](https://user-images.githubusercontent.com/19987739/45597620-11732c00-ba0a-11e8-9cf5-9559febc0e0c.png)

### 感情・トピック分類
![image](https://user-images.githubusercontent.com/19987739/45597554-0a97e980-ba09-11e8-97be-4352955a2a68.png)

### キャプション検索・画像検索
![image](https://user-images.githubusercontent.com/19987739/45597560-2a2f1200-ba09-11e8-96e8-a174b5df1ca2.png)

### 機械翻訳
![image](https://user-images.githubusercontent.com/19987739/45597573-46cb4a00-ba09-11e8-9c22-54c88f46fd94.png)

## コメント
コンセプトは順当でスッキリしたものだと思いました．220万の単語に対して，少なくとも10枚/語彙 の画像を CNN モデルに突っ込むので結構重たい処理だと思うのですが，さすが Google だけあってやっている実験の量が違いますね．数の暴力．
今回はそれぞれの手法は単純なものですが，各タスクに対してこれらの手法はどんどん最適化され洗練されていくと思うので，今後の発展が楽しみです．

**Comment by yukiar** [comment]
Inverse picturebook は多言語のみ？

**Comment by KAWAYu** [comment]
（すごい細かいですが、まとめでのBLEUの綴りが多分間違っていたので、公開する際は直しておくといいかもです）
