### ISSUE TITLE
Self-Attentive Residual Decoder for Neural Machine Translation

### ISSUE THREAD

**Issue by NomotoEriko** [OnizukaLab/ConferenceProceedings#2]
## 一言でいうと
機械翻訳において翻訳元にアテンションを張り，翻訳元の文脈を大域的に考慮することは一般に行われる．
提案手法では訳出済みの文の要約を用いて次の単語を予測することで翻訳先の文脈も大域的に考慮する．
3つの言語対において類似の手法を超える翻訳性能を達成．

### 論文リンク
https://arxiv.org/abs/1709.04849

### 著者/所属機関
Lesly Miculicich Werlen, Nikolaos Pappas, Dhananjay Ram, Andrei Popescu-Belis
- Idiot Research Institute, Switzerland
- E´ cole polytechnique f ´ ed´ erale de Lausanne (EPFL), Switzerland
- HEIG-VD/HES-SO, Switzerland

### 投稿日付(yyyy/MM/dd)
2017/09/14

## 概要
![2018-06-29 0 10 55](https://user-images.githubusercontent.com/19987739/42043640-e6490e58-7b31-11e8-9b61-c48cfc019466.png)

機械翻訳においてデコーダはアテンション機構を通じて全ての翻訳元の文脈にアクセスするが，
翻訳先における文脈情報は隠れ状態の固定長のベクトルで表現される．これが長期の情報保持を学習する上でボトルネックになる．
seq2seqでは，直近の単語にバイアスがかかることと構造的な組成を十分に捉えられないことがネックである．
これを避けるために著者らはself-attentive residual recurrent decoderを提案している.

この論文における貢献は以下である．
- self-attentive residual learning のいくつかのオプションの提案および比較
- 言語に依らず一貫した性能向上の実証（en2ch, sp2en, en2ge）
- アブレーション（切除）研究を通じた提案手法の分析

## 新規性・差分
翻訳先の文脈情報を考慮する簡潔なモデル Self-attentive residual connections を提案

## 手法
過去の全訳出語という可変長の入力を扱うために，ターゲット側の要約ベクトルd_tを定義．
d_tはtまでの訳出文の表現と見ることができる．
d_tの構成の仕方には以下の2つがある

### Mean Residual Connections
tまでの訳出語{y_1, ..., y_t}の平均

### Self-Attentive Residual Connections
tまでの訳出語{y_1, ..., y_t}の重み付き平均
重みはアテンション機構 (shared self-attention mechanism) によって決定される
アテンション機構は単語間の非連続的な依存関係をモデル化することを目的とし，recurrent層の補完的なメモリとして機能する．

## 結果
![2018-06-29 0 15 41](https://user-images.githubusercontent.com/19987739/42043654-ebb9f078-7b31-11e8-86ec-fb1f1a846206.png)

_memory RNN_ はベースラインとほとんど同じBLEUを示し，また，アテンションはほとんどt-1に張られる．
_self-attentive RNN_ はベースラインに劣る．
これは隠れ層が反復表現とアテンションを同時に学習しなければならないというオーバーヘッドに起因すると考えられる．
提案手法はベースラインを超え，_self-attentive residual connections_ が最高スコアを出している．
手法が単純でパラメータ数がほとんど増えていないことにも注目すべきである．

## コメント
意外とただ平均をとっただけでもいいスコアが出ているのは面白いと思った．

**Comment by yukiar** [comment]
Transformerと比較してほしい

**Comment by NomotoEriko** [comment]
スライドを https://www.slideshare.net/OnizukaLab/nomoto-n18-1124 にアップしました．

**Comment by NomotoEriko** [comment]
residual decoder の嬉しみの一つに，ある単語へのアテンションの重みを一回計算したら以降再計算の必要がないというのが有ります．これが既存のアテンション機構と違うところで，既存のアテンション機構（Self-attentive RNN）ではタイムステップごとに毎回重みの再計算が必要になります．

ということで，residual decoder は軽い．
