### ISSUE TITLE
Graph-to-Sequence Learning using Gated Graph Neural Networks

### ISSUE THREAD

**Issue by 21335732529sky** [OnizukaLab/ConferenceProceedings#20]
### 一言で言うと
グラフ表現を使ってRNNなしで言語生成すると、既存手法以上のパフォーマンスが出ました
### 論文リンク
[リンク](http://aclweb.org/anthology/P18-1026)
### 著者/所属機関
- Daniel Beck / School of Computing and Information Systems University of Melbourne, Australia
- Gholamreza Haffari / Faculty of Information Technology Monash University, Australia
- Trevor Cohn / School of Computing and Information Systems University of Melbourne, Australia
### 概要
多くのNLPアプリケーションはGraph-to-Sequenceの問題と捉えられる。
既存手法では、Neural Architectureを使って、文法ベースより良い結果が得られているが、未だに
線形化ヒューリスティックやRNNなどに頼っている。
この論文ではグラフに含まれる構造化された情報を全て利用するモデルを提案する。
実験から、この論文の提案手法は、AMRからの生成タスク、機械翻訳両方においてs2sを上回った。
### 新規性・差分
Levi Graph変換を用いて、パラメータ数爆発問題の解決と、各グラフに適したエッジのベクトル表現の
取得を実現している
### 手法
seq2seqのenocder部分に、Gated Graph Neural Networkを適用。
入力グラフは、有向非巡回グラフをLevi Graphに変換したものを使用
### 結果
- 生成タスク
![2018-09-17 14 29 23](https://user-images.githubusercontent.com/29420753/45627823-b7d43580-bacd-11e8-9b68-742670200cbc.png)
- 翻訳タスク
![2018-09-17 14 29 37](https://user-images.githubusercontent.com/29420753/45627839-c4f12480-bacd-11e8-9b15-db62b3de4373.png)
![2018-09-17 14 29 47](https://user-images.githubusercontent.com/29420753/45627890-dcc8a880-bacd-11e8-84a8-132b4c7deb7a.png)

**Comment by bmiura** [comment]
「既存のやつはグラフの情報を一部落としたり、線形にしたりしちゃうので、そのまま入れたい」という話だったのに、有向グラフを無向グラフっぽくしたり、変なエッジを追加したりするのは平気なのか…
