### ISSUE TITLE
A Deep Ensemble Model with Slot Alignment for Sequence-to-Sequence Natural Language Generation

### ISSUE THREAD

**Issue by tanaka504** [OnizukaLab/ConferenceProceedings#3]
## 一言で言うと
Natural language generation using a deep ensemble model considering aligned Meaning Representation (MR)

### 論文リンク
[A Deep Ensemble Model with Slot Alignment for Sequence-to-Sequence Natural Language Generation](https://arxiv.org/abs/1805.06553)

### 著者/所属機関
Juraj Juraska, Panagiotis Karagiannis, Kevin K. Bowden, Marilyn A. Walker
Natural Language and Dialogue Systems Lab, University of California, Santa Cruz

### 投稿日付(yyyy/MM/dd)
2018/05/18

## 概要
自然言語生成をする際，Meaning Representation (MR)を考慮して生成することは文の意味的整合性と構造的整合性をとることができる．(MRとは複数の対話行為(DA)から成り，DAは情報のタイプ(slot)と発話中の表現(value)の対から成る．) しかし，従来の統計的手法では人手でルールを定める必要があり，ニューラル的手法ではslotの対応をとるために膨大なデータが必要であり，生成された文は流暢性を損なう．よって，MRの情報を用いた新しい生成器の提案，slotの対応を自動でとるシステムの構築を目的とする．

## 新規性・差分
 - 文とslotとの対応が取りやすくするようにmodifyする前処理システムの構築
 - 生成文と入力slotとの対応が取れるような生成器の構築

## 手法
- 前処理
1. value の頭文字が母音の場合，slot の単語が含まれている場合を区別して新しいslot に格納
2. 正解文に指示語が含まれている場合，どこに指している表現があるかの情報を追加
3. 構文解析をして同格関係を抽出

- モデル概要
単純な注意機構付きSeq2Seqモデル
- エンコーダ部
エポック数の違う２種類のBidirectional LSTMを用いたものとCNNを用いたものとでアンサンブル
- デコーダ部
LSTMを用いたデコーダ
３種類のモデルからそれぞれ１０単語の候補を生成し，スコア（与えたslotの内どれだけ正確に生成できているか）が最も高くなるようにbeam searchを行う

## 結果
- 評価指標
BLEU, NIST, METEOR, ROUGE

- 結果
前処理を行わないデータと前処理を行ったデータとで比較した結果，前処理を行ったデータの方が良い結果が出た．
３種類のモデルそれぞれとアンサンブルモデルとで性能評価した結果，BLEUとNISTではエポック数が少ないBi-LSTMモデルが最も高い値を示し，METEORとROUGEではアンサンブルモデルが最も高い値を示した．

## コメント
竹林さんのインターン内容に実装が似ていると思いました．

**Comment by NomotoEriko** [comment]
長いエポックと短いエポックでアンサンブルするお気持ちがわからない...
@tanaka504 なんか書かれてたりしますか？

**Comment by yukiar** [comment]
アンサンブルしたら性能下がってないですか？
