### ISSUE TITLE
Dynamic Multi-Level Multi-Task Learning for Sentence Simplification

### ISSUE THREAD

**Issue by NomotoEriko** [OnizukaLab/ConferenceProceedings#31]

**Comment by NomotoEriko** [comment]
soft sharing について，
\theta がパラメータ全体で， \theta_s は単純に共有する層のパラメータって説ないですか？

**Comment by Nishihara-Daiki** [comment]
## 一言でいうと
ポインタコピーメカニズムのseq2seqに、マルチタスク・マルチ階層を組み込んだら、SARI、FKGL、人手評価で優れた。

### 論文リンク
https://aclanthology.coli.uni-saarland.de/papers/C18-1039/c18-1039 [[PDF](http://www.aclweb.org/anthology/C18-1039)]

### 著者/所属機関
Han Guo, Ramakanth Pasunuru, Mohit Bansal
The University of North Carolina at Chapel Hill

### 投稿日付(yyyy/MM/dd)
2018

## 概要
+ 文の平易化で、有効な入力文も論理的に含めたい（含意）
+ Baselineはポインタコピーメカニズムのseq2seq
+ 提案手法では、マルチタスク（含意・言い換え）、マルチレベル階層（含意が高、言い換えが低）
+ タスクの切り替えは、動的（多腕バンディット）
+ SARI, FKGL, 人手評価で優れた

## 新規性・差分
+ マルチタスク・マルチレベルにした
+ タスクの混合比を動的に決定した

## 手法
![2018-10-17 13 47 22](https://user-images.githubusercontent.com/15244574/47062823-35957900-d213-11e8-994b-a2ccece64713.png)
+ 低層（語彙統語層）では、言い換えタスクとパラメータを共有
+ 高層（意味層）では、含意生成タスクとパラメータを共有
![eq2](https://latex.codecogs.com/gif.latex?L%28%5Ctheta%29%3D-%5Clog%20P_f%28y%7Cx%3B%5Ctheta%29&plus;%5Clambda%7C%7C%5Ctheta_s-%5Cphi_s%7C)

## データセット
  | Train | Valid | Test
-- | --: | --: | --:
Newsela | 1,070 | 30 | 30
SmallWiki | 89,042 | 100 | 205
LargeWiki | 296,402 |   | 359
SNLI   &   MultiNLI <br> (含意生成用) | 276,720 | 26,159 | (*)
Wieting&Gimpel <br> (言い換え用) | 5.2M | 53K | (*)
(*) Valid と Test を合わせた数を Valid に記入している

## 結果
![2018-10-17 14 42 56](https://user-images.githubusercontent.com/15244574/47064589-ff5bf780-d21a-11e8-8491-d8f4c3b3c2a8.png)
![2018-10-17 14 44 00](https://user-images.githubusercontent.com/15244574/47064615-26b2c480-d21b-11e8-8b28-0456db9ac5ca.png)


## コメント
アブスト読むのに一日かかった
