### ISSUE TITLE
Multi-Task Neural Models for Translating Between Styles Within and Across Languages

### ISSUE THREAD

**Issue by bmiura** [OnizukaLab/ConferenceProceedings#38]
## 一言でいうと
スタイル変換(Formality Transfer)とスタイル気にする機械翻訳(Formality-Sensitive MT)をマルチタスク学習した。

### 論文リンク
http://aclweb.org/anthology/C18-1086

### 著者/所属機関
Xing Niu, Sudha Rao, Marine Carpuat, University of Maryland, MD, USA

### 投稿日付(yyyy/MM/dd)
2018/06/12

## 概要
スタイル変換(Formality Transfer)とスタイル気にする機械翻訳(Formality-sensitive MT)をマルチタスク学習した。
FT：SOTA更新
FSMT：FSMT側のデータに制約(事前にデータ選別が必要)つけなくても、それなりの結果に

## 新規性・差分
・FTとFSMTマルチタスク学習した
・FTと一緒に学習することで、事前にデータ選別することなくFSMTできた

## 手法
<img width="617" alt="method" src="https://user-images.githubusercontent.com/38415808/47323835-6bfe4880-d698-11e8-83cd-a9468747a293.png">

## 結果
<img width="628" alt="result1" src="https://user-images.githubusercontent.com/38415808/47323870-9819c980-d698-11e8-96af-6090bf69b428.png">
<img width="614" alt="result2" src="https://user-images.githubusercontent.com/38415808/47323873-99e38d00-d698-11e8-9003-82c446416ad5.png">
<img width="614" alt="result4" src="https://user-images.githubusercontent.com/38415808/47323879-9ea84100-d698-11e8-9343-cbae84a3304b.png">
例
<img width="619" alt="example3" src="https://user-images.githubusercontent.com/38415808/47323898-b2ec3e00-d698-11e8-9f32-704f7b7a46b1.png">
<img width="618" alt="example5" src="https://user-images.githubusercontent.com/38415808/47323900-b4b60180-d698-11e8-9c24-b613d5a3f06d.png">

## コメント
※めっちゃねむい

**Comment by NomotoEriko** [comment]
:zzz:
