### ISSUE TITLE
A Comparison of Transformer and Recurrent Neural Networks on Multilingual Neural Machine Translation

### ISSUE THREAD

**Issue by chikurin66** [OnizukaLab/ConferenceProceedings#39]
## 一言でいうと
RNNとTransformerを比べた．（bilingual / multilingual / zero-shotで）

### 論文リンク
http://aclweb.org/anthology/C18-1054 

### 著者/所属機関
Surafel M. Lakew, Mauro Cettolo, Marcello Federico

### 投稿日付(yyyy/MM/dd)
COLING2018

## 新規性・差分
bilingual, multilingual, zero-shotで定量的な評価を行った．
TransformerとRNNの翻訳性能について調査した．
zero-shotにおいて言語の近さがどう影響するか調べた．

## 結果
![image](https://user-images.githubusercontent.com/20056490/47327102-cbfbeb80-d6a6-11e8-84db-2ac8382b67c9.png)

**Comment by NomotoEriko** [comment]
seq2seq はオワコン
