### ISSUE TITLE
Classical Structured Prediction Losses for Sequence to Sequence Learning

### ISSUE THREAD

**Issue by 50kawa** [OnizukaLab/ConferenceProceedings#7]
## 一言で言うと
アテンション付きseq2seqの目的関数をいろいろ比較してみました。

### 論文リンク
[Classical Structured Prediction Losses for Sequence to Sequence Learning](http://aclweb.org/anthology/N18-1033)

### 著者/所属機関
Sergey Edunov, Myle Ott,
Michael Auli, David Grangier, Marc’Aurelio Ranzato
Facebook AI Research
Menlo Park, CA and New York, NY

### 投稿日付(yyyy/MM/dd)
2018/05/18

## 概要
ビームサーチを行うアテンション付きseq2seqの目的関数をいろいろ比較してみました。
MaxMargin等の目的関数もseq2seqに当てはめて再定義しました。
独英翻訳のデータセットであるIWSLT'14で翻訳のタスクで評価しました。

## 新規性・差分
MaxMargin等の古典的な目的関数をSeq2Seq用に変換して性能を評価するという点で新規性がある。

## 手法

- 単語の尤度から目的関数を定義した手法と、文の尤度から目的関数を定義した手法が存在する
- 文の尤度を用いる手法ではビームサーチを使用。いくつか生成文の候補と尤度が計算される
- u*は、候補文の中でBLEUが最大の文を指す

### 単語の尤度に基づく目的関数

- TokNLL
普通に正解データの尤度を最大化するような目的関数。
seq2seqの論文で目的関数に言及されていなければこれが使われているというくらい基本的な目的関数。本論文のベースライン

- TokLS
TokNLLだと正解の語の尤度だけが高くなるという問題があるので、語彙の分布と正解の分布のKLdivergenceも考慮する

### 文の尤度に基づく目的関数
- SeqNLL
TokNLLみたいに正解文の尤度を最大化する目的関数。u*の尤度-候補文全部の尤度

- Risk
コスト関数を最小化する目的関数。今回は1-BLEU値。ただし重みとして文の尤度をかけている

- MaxMargin
u*のスコアと候補文中の最大の尤度を持つ文のスコアの差を最小化する。スコアはコスト関数とソフトマックス関数の和で計算される

- MultiMargin
MaxMarginでは最大の尤度を持つ文のみu*とスコアを比較したが、MultiMarginでは全ての候補文とスコアを比較、差の和が最小になるように学習

- SoftmaxMargin
高すぎる尤度をコスト関数の値に合わせるように目的関数を設定
u*の尤度-候補文全部のコスト関数とソフトマックス関数の和

## 結果
単語の尤度に基づいた目的関数より文の尤度に基づいた目的関数の方がいい結果になった。
また、両方を組み合わせることでよりいい結果になった。
単語の尤度に基いた目的関数でパラメータを初期化してから文に基づいた目的関数で学習させても、両方を組み合わせた場合と同じような結果になった。

## コメント
目的関数難しい。ただ目的関数を決めるための着想みたいなのが理解できれば今後役に立つなと思った。この論文だと、古典的な目的関数をseq2seqに応用したというところが着想にあたるのでは

**Comment by NomotoEriko** [comment]
@50kawa できれば結果の表を載せていただきたいです．

結果のところでおっしゃっている，両方を組み合わせたものとはどんなものでしょう？（結果で触れるなら手法でも触れていただきたい...）

**Comment by NomotoEriko** [comment]
@50kawa 結果の分析がこの類の論文では重要だと思うので，その辺りの説明をリッチにするといいと思います．

**Comment by 50kawa** [comment]
![image](https://user-images.githubusercontent.com/19972398/42546893-699ca6c6-84fa-11e8-9ff9-1ccc3d0f889f.png)
この結果から目的関数をそれぞれ比較出来るのですが、論文で分析として書かれてたのはやっぱりtoken-levelよりsequence-levelの方が良かったぐらいしか分析されてないです。（数値の差があまり大きくなかったため）。なので追加で分析を加えるため、token-levelとsequence-levelを組み合わせる実験をして、
![image](https://user-images.githubusercontent.com/19972398/42547216-f936c004-84fb-11e8-9e9c-853bcf1dc8ab.png)
から組み合わせることで結果が良くなると分析していました。
